apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  namespace: {{ .Release.Namespace }}