apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission-patch
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    app: {{ include "nginx-ingress-controller.fullname" . }}-admission-patch
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ include "nginx-ingress-controller.fullname" . }}-admission-patch
      labels:
        {{- include "nginx-ingress-controller.labels" . | nindent 8 }}
        app.kubernetes.io/component: admission-webhook
        app: {{ include "nginx-ingress-controller.fullname" . }}-admission-patch
    spec:
      containers:
        - name: patch
          image: "{{ .Values.admission.patch.image.repository }}:{{ .Values.admission.patch.image.tag }}"
          imagePullPolicy: {{ .Values.admission.patch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ include "nginx-ingress-controller.fullname" . }}-admission
            - --namespace=$(POD_NAMESPACE)
            - --patch-mutating=false
            - --secret-name={{ include "nginx-ingress-controller.fullname" . }}-admission
            - --patch-failure-policy=Fail
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: {{ include "nginx-ingress-controller.fullname" . }}-admission
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000