apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission-create
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
    app: {{ include "nginx-ingress-controller.fullname" . }}-admission-create
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ include "nginx-ingress-controller.fullname" . }}-admission-create
      labels:
        {{- include "nginx-ingress-controller.labels" . | nindent 8 }}
        app.kubernetes.io/component: admission-webhook
        app: {{ include "nginx-ingress-controller.fullname" . }}-admission-create
    spec:
      containers:
        - name: create
          image: "{{ .Values.admission.create.image.repository }}:{{ .Values.admission.create.image.tag }}"
          imagePullPolicy: {{ .Values.admission.create.image.pullPolicy }}
          args:
            - create
            - --host={{ include "nginx-ingress-controller.fullname" . }}-controller-admission,{{ include "nginx-ingress-controller.fullname" . }}-controller-admission.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name={{ include "nginx-ingress-controller.fullname" . }}-admission
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: {{ include "nginx-ingress-controller.fullname" . }}-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000