apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-ingress-controller.fullname" . }}-admission
    namespace: {{ .Release.Namespace }}