apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission-patch
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    helm.sh/chart: {{ include "nginx-ingress-controller.chart" . }}
    app.kubernetes.io/component: admission-webhook
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: {{ include "nginx-ingress-controller.fullname" . }}-admission-patch
      labels:
        helm.sh/chart: {{ include "nginx-ingress-controller.chart" . }}
        app.kubernetes.io/component: admission-webhook
    spec:
      containers:
        - name: patch
          image: docker.io/jettech/kube-webhook-certgen:v1.5.1
          imagePullPolicy: IfNotPresent
          args:
            - patch
            - --webhook-name={{ include "nginx-ingress-controller.fullname" . }}-admission
            - --namespace=$(POD_NAMESPACE)
            - --patch-mutating=false
            - --secret-name={{ include "nginx-ingress-controller.fullname" . }}-admission
            - --patch-failure-policy=Fail
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
      serviceAccountName: {{ include "nginx-ingress-controller.fullname" . }}-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000