apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create