apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: admission-webhook
  name: {{ include "nginx-ingress-controller.fullname" . }}-admission
webhooks:
  - name: validate.nginx.ingress.kubernetes.io
    matchPolicy: Equivalent
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          # - v1beta1
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
      # - v1beta1
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "nginx-ingress-controller.fullname" . }}-controller-admission
        # path: /networking/v1beta1/ingresses
        path: /networking/v1/ingresses