apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "nginx-ingress-controller.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
data: