apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "nginx-ingress-controller.fullname" . }}-controller-admission
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
  selector:
    {{- include "nginx-ingress-controller.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    app: {{ include "nginx-ingress-controller.fullname" . }}-controller