apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-controller
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  # externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    # {{- include "nginx-ingress-controller.selectorLabels" . | nindent 4 }}
    # app.kubernetes.io/component: controller
    app: {{ include "nginx-ingress-controller.fullname" . }}-controller
