apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
  name: {{ include "nginx-ingress-controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nginx-ingress-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-ingress-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}