{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  namespace: {{ .Release.Namespace }}
{{- end }}
