apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nginx-ingress-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  name: {{ include "nginx-ingress-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nginx-ingress-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nginx-ingress-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}