apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-ingress-controller.fullname" . }}-tls
  namespace: dev
type: kubernetes.io/tls
data:
  server.crt: |
       -----BEGIN CERTIFICATE-----
MIIFAzCCAuugAwIBAgIJAJ9swboulMKVMA0GCSqGSIb3DQEBCwUAMEoxCzAJBgNV
BAYTAlVTMQ8wDQYDVQQIDAZCb3N0b24xETAPBgNVBAoMCEludGVybmFsMRcwFQYD
VQQDDA4qLmludGVybmFsLmNvbTAeFw0yMzAxMDIyMjExMzdaFw0yNDAxMDIyMjEx
MzdaMBMxETAPBgNVBAMMCGludGVybmFsMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
MIICCgKCAgEAr6uFaDmlfOLdhvONeon/qwUjmOex2R5N+zS+6mLTL3NL50QkfprR
mQ7HLvdKFGwtMEvo+0TJB0aXSYeytgvDyvG6NFx5j2yBnj/gCirn9qxVDWAtCJVP
zpFovOK/wP9pkfJxq7zNiL84KOWvojHCcvjwlgv7uCJDAsaMn1wZ4PqJt5GzmK33
VDfbgk/OEmqV8dkSqIyB9iUy+FFnB/IVtUEMW1Jv30Ghpj3Q+LwfHa+0FO5xxqKI
IQG24snyRtnR2RJvOySCW6tDf4DS6atU9ouaztTi+jhjCoyRxH4YrO7AScsfujsL
9zdAkhlS6MeHSuhW7THIs/jxIbd0yAUypo+lX/6O3C53ZZJ+g/JhZk/RIBqez7GQ
jUPjJ+FYFRiXbv8FytL3ebpiCkCug7vEqh2wpLGYfBfQXeV6RCoS5ZH8oV0vztSG
KC+k1a+xgCjIWvDUpz2bi1O6hkLNhj7NLoANggJeU1PVBp6l7chKPYNarMqSkVU7
PEas994WLCX3zYkz6OHXgzjwb3HRFnky6Uqeaq5NvkYpvaVWFs/egRHUyT4a5hSy
SRQT8aC2ia3feyUfoMk36y3l6+j0tN39voPbmCaTydtjb2Z7/RcRHe5r6Lckl7z4
AfaBMKZ/meUH8u4oSG5mAeetIBEUXvSP7iBoftCr3dZPWozikmF/yTkCAwEAAaMj
MCEwHwYDVR0RBBgwFoIOKi5pbnRlcm5hbC5jb22HBBECAgowDQYJKoZIhvcNAQEL
BQADggIBALDdKAafUDpuD6Xd7WQ+AZ7jc8Zym4u0l1oJ5eiVsk0+2kBb/qCagpfU
IGgHW9poodpgaU+1vjfVTXs9rZsleYOPykWNTENGlp6ySLiGea55FNHCRYxgufr6
u2bOMAwoYkdJAAs5Bnj/L4W/mWD3uNcuVUPLKfmx/X38KM1jmuGC97GxUuzuaA2r
qZBCCVHyouKD8KEN2yYF6AZDIihptYASk0icBrNA7yq+IFpQx7oljJ1PCtoSi8Fg
piFtx62IOGNzN1O5yhBtcWfDFP/kLrZdaaChrU8ianVpW+nbBszql1OGp3UMtgtV
033iL4aQzm47cJtNM6bUTsrHHpaok6BsbkYdlLDpYWddYyd6NrohXIKmNEdtumHI
M3PmK/2GMnkTG0m5Jw+JjBptCojP6UAecsoVWHlvmGUZw2az5nOWjQZAsx/vYmrz
6l+80252npubT3tsbNh2L++NrId1vXDWjQ6gthUBx7cuH6Pgsx+MAvVz9zj0n3yS
A3HU/WWJYcPxrvAxp3TQABz29CTxE3idtsdxoV4VDFBoOJwujguVgllIemIm7xUk
H0pvcfE7KqXjRO5yunjSXNRAnLkfArjURvaFP+FBGeVlg1Vt1dPoczdyvJAMB9Yz
c+BUFkrQH1cEnx14fCJdvvKkGMDjTsQryXMsob0/F835iMViF0W8
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
MIIFEDCCAvgCCQCJlq0zKWrj+DANBgkqhkiG9w0BAQsFADBKMQswCQYDVQQGEwJV
UzEPMA0GA1UECAwGQm9zdG9uMREwDwYDVQQKDAhJbnRlcm5hbDEXMBUGA1UEAwwO
Ki5pbnRlcm5hbC5jb20wHhcNMjMwMTAyMjIwMjA4WhcNMjQwMTAyMjIwMjA4WjBK
MQswCQYDVQQGEwJVUzEPMA0GA1UECAwGQm9zdG9uMREwDwYDVQQKDAhJbnRlcm5h
bDEXMBUGA1UEAwwOKi5pbnRlcm5hbC5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4IC
DwAwggIKAoICAQC8xhvGnipzJYov7DOLzvkMGX9o+ZgMiIl1HxLrZX49VXeaHv9W
au4Fkrm+FCNDT4X06pdK9PnglzYK2pgzVxaQkLLq8uEqfTKP/DGtinwaxcHm88G2
lzHVoaEMD9mLPQpKhUDWx8C4X9h+i2AIFcBeaSkr0pxct1qx2iXGZ8zofC48mCzg
t+wu4rWSQCQLqCNQBpgqRGhoI6VDglhRHYZLMQgpQF46Hj+dfR1OAIAgkqM4wuJL
IvQhiKa9uCLrlG84ZxXjj5BGEXL+D4iLb9TmFbzoBmpbJeOgnoKQhC2lluVx3j24
i3N7uK/1rkQQDKUknrTdfYWIi7LUVHWvZhsGDM86I+1/pRggjL9pQFTDxWQA59F1
zXYebOhUGVN98fdvoDd69/X3vDo5M9xsAYFYzaRZMvovkyV0koKf0lBbKBMhEagG
0i+htZ4xaUdNeX8KTIHlfQGolb5mIjQwyt3FspsbpAuOiyCXov6hzo2LZtvjo9Gl
LusC2kGyoLc3bRlx6tjVUO1dvD8NshUCb0ZMCfgce9e/w5/rAARBaMqSOKAtXgWv
+LiPwmnDHlprCf5VcpcbjgcnxQ1SRdArAFO3d+q9c2TokrpJ5UqYQuAnYg/9zSes
ZBLKkm49M7etMzAUPUMcng2H3dnxmcdA9ZL+9zbLi6Z+FUB7EAZXIRry8wIDAQAB
MA0GCSqGSIb3DQEBCwUAA4ICAQAwlvHOaS+pRMcL1KtuevMM2dYrYg6UCIvmPzut
nev/rvBJ0Yq2+Bj2nTBr5WNu8VuEs3179rLFw6ciDwXtsdgeKE48Me8Gib4SRHk/
IYYmeD4vg3GJkfWx09n6igrnMicARYEdo5sG4zcBAXomDQ68Op42tVlpbupcEIjG
OYqkDvCb9Y/alJBrflR8+vSIvD/KAAY6/3CDAjP6EpiX6QLsV46UrepZouL4r9wZ
Sb/t0oiBbXxM4zAkVJ8j08j7sDP5cuZ1LCkl3Qc9AFVKVc7mmlh0b/ldiey+LCXm
gqMearpCyf9x8m6U88Fi0F1gTKZyZprMv+/GQJrIId9gaebmlXdncyvKayYLG9P6
VIkfPIts2evpL92sebFOv5TH4ohtfdZBNA8kuxCqrZZC5ZSVDHnCEQ0sYEwUw37p
4ebCInCilKMSuKC84n1D+TCd1qP1/4/gmnsL0KATvRRsMEec7iabmThO2Ly3DmQq
UtogYMImDrR1DjxKcmjaPEBe54yMEpQ2Vkdc4UDVNiSolmbv2Jxcqq5a0r/1ORK/
easYbz5BXsyoQ6Ac1sdtaO3K07iGz7xzThM2ORWJ9147ShuU5ExNw9iRnyi3wDtQ
YMuuI3a5XhtrhiUqKmmyt08IyG4OSKeiEqxPMrALKME7hG7I/HgWx4hav3bgCVjz
u1gpkA==
    -----END CERTIFICATE-----
  server.key: |
       -----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEAr6uFaDmlfOLdhvONeon/qwUjmOex2R5N+zS+6mLTL3NL50Qk
fprRmQ7HLvdKFGwtMEvo+0TJB0aXSYeytgvDyvG6NFx5j2yBnj/gCirn9qxVDWAt
CJVPzpFovOK/wP9pkfJxq7zNiL84KOWvojHCcvjwlgv7uCJDAsaMn1wZ4PqJt5Gz
mK33VDfbgk/OEmqV8dkSqIyB9iUy+FFnB/IVtUEMW1Jv30Ghpj3Q+LwfHa+0FO5x
xqKIIQG24snyRtnR2RJvOySCW6tDf4DS6atU9ouaztTi+jhjCoyRxH4YrO7AScsf
ujsL9zdAkhlS6MeHSuhW7THIs/jxIbd0yAUypo+lX/6O3C53ZZJ+g/JhZk/RIBqe
z7GQjUPjJ+FYFRiXbv8FytL3ebpiCkCug7vEqh2wpLGYfBfQXeV6RCoS5ZH8oV0v
ztSGKC+k1a+xgCjIWvDUpz2bi1O6hkLNhj7NLoANggJeU1PVBp6l7chKPYNarMqS
kVU7PEas994WLCX3zYkz6OHXgzjwb3HRFnky6Uqeaq5NvkYpvaVWFs/egRHUyT4a
5hSySRQT8aC2ia3feyUfoMk36y3l6+j0tN39voPbmCaTydtjb2Z7/RcRHe5r6Lck
l7z4AfaBMKZ/meUH8u4oSG5mAeetIBEUXvSP7iBoftCr3dZPWozikmF/yTkCAwEA
AQKCAgBzIa7liCJ1nxohAC6RSTBPHace53sgGURyhzc41lwilSYCBB8G+uCzt4PD
vD7I870KEjY3t/Uo15L/lfgCZ+OCdrra5mClJzAsTyC+iTBN8tQrWAUrwu/zKknC
wbl6++psxMDLFYp/PRPJef+KBaKzR4QmUuQ+4fWZNBelue8cDBeGP++8+QdIIvOy
jCs61rA/OU2JOc1TTT4CkRc9leO0T1WR5I19fL48/fafjmu2QRl9PmlDDfK57y21
pTUsSkXGRtavpFXrTmuGfR++FZQxoX1sYQoBhEMk/svqQ9pYPIG5226H13sYIxYm
qoI0HdEFvxB5lE895MHknx/il8WBXSbbpmPXhjsHEPKs6ogzNWrvsTd7O31EwEfI
sXASuwlyvedfkziJM2HLynj+mniMlvTtz2NDfGLz7KuLyzb38qlKlGbGRuTsL2dO
noFzf9+zceBVa1Qg9ENoDeoUs9M18DVRbuqaX5QzjLhpxLUj6mLK2V3QllSRALUi
Fis8PXmIK95aNyfpDAk5l1tHldJuI8UGi7PQdfjTssR1liU+1r+vdZkWyv/qc+/D
1+zkzzm4Nd0TLoGAj0a6V6LRg0R65edseCjF6ZKrkygFdNZMpBcUMg/khxLZ4Sxn
Z0k+slNre1BN4MvAf/xmTo4aAnPCawP2gqR75Jzq9Wh30BlAAQKCAQEA6LrBu6dL
PHyD9x65kNfaWCo1Wln2UcfKtbAxRj0oEgEClKjMMGqHZyVkGItJovmB/Hu7P4NH
JBnoSnlYIi1ZvGcBx3lyfaZbyajclakGxwzWgfkta0AB0KF3h1mlAUFBP1VZ7mO2
E2vyyu6YyRWLOPlhOFrLG+C9rAm1CkNxPRlvAjn2Ms/P0E4OgrEld/VRFg8IH2Td
Fhjg50dD1m256IDKyeNg2zFZFjbSr+QQ8Uai3xeffAUn/eQBDzVpDq5VSj06A3Sr
RDX/6uhA2Lu9IiEFE5cIHCxPTxRE0EkiWu9kWFwfOdYNAVE2oBOeangBmIbaCroU
CIWn7IoUUSAHAQKCAQEAwTwyIw58hn3UbFmnBKvwNRONRXKAScCnGxHd5ldojIvy
Z0BadA+RCEOpwU795xE0uHEzOvUBRIqjehtVpuWTNxXCT3hPw/MXR5cv2khzRUuj
OcQFXNB5M+vUgXWtFvkbJjynE0mRCEAl/O/LpQwduA3q2VqqTk1vE4VAwek4o/uQ
as48Xaxj5pgkL1J9Xxzclz29uGDSD+vN2C+sn4tzH5wlbPdQwEIb4g1sVDugw6mh
xslYiWRC00WdbRlPrvJZMKQHEu0pQdMk+FZRgRCQwEE1T1LfvRMF7dAkaYspIWAj
sQxtktF2eZG01N5e4ppZulZ0DSmJSOVOxKiEl8g6OQKCAQAEh/5VpQA2AUagfRyn
0UwTA19ejvnYxccQmombEH3DO/nM4yx2lNxmCbhVMgERB0Kco9wVdHziGw8GxC4P
HEru/CJwu9Ca2a5X0s3YrB3RqlJS3YMg33Ipmbs2C2zHBXo7vXGuzoow/p0Pjm2z
HJRFW7Wk3z+tH0cSHm5D8OQ3iFM8+9vrSViGeb6WlNRh7YjSoSBLXC9hysI2PpD3
j9Naz4cjPyYXnnJZmF+pxQr/Z5ysM02LoJ4St2m93hBZlNNcSqzifFcJUPPWowcA
MUeRbosmwn4J7mLs6zwbwhDFLHwLrF9/RMekCuzBWSBwej2ttpJwOwdA0zldxaJ3
oeQBAoIBAFv5pPuet5Lkbams+px0on8A8Wsu1vVD58YwuOgcjrznF9ghf2xixGuk
mTZTvPKw8+EesH3NhG71dl52iExKVcoQZ06gO4dPO7NtuO8zMPq4x9aFAPBuomIe
TCXatyqKI2wNzpCVoZzFu88q7EmA/NxQc4pFZ26h2M73zB0AP19+K/1KcN09Yset
fvuvTdFp0W2Di7wpCZNeb7oI5yeBnqhbEE1PYnZAgTkVnoxxXVIEeeY+jA/JUy1w
oz/8njrtS5qlWGCf1dVpBN3XaDAAjIWWBCPflHNQjK/nNI2wGUGzmwl4mucZIEU5
H1N7DLrbMP5KjC5/qMKzssxUUdhVC7ECggEAEChvW9YEHbQVCf4iRh/USxgoqolS
lYbEieV3nzel6vb15NWfIKngYWizemby3XkhTCcnwHrXjlgYMCIjqw5ih6Uu3gbA
ug+qe9whjU8IQMh56NWOcqw7eiCbGONPtyNqox1SA6CcgoBCSx9eRT3/O8mpVAXL
QvXB3m6b/SpaDCyJkgNXlKVPTZU9IaF7IeA9CRD2g3LPp8N/73gbN7+vVvaWiM2h
ECsYpOYQxWMY+6apJ5LhUUHuDwiimbw7ITW431oZU9eg9DC/12acLi3zFyMWqQmQ
IKD9fM3rdJAlMNTA7Tt5V4gPcEhY1lIjGqegUuDdM7hP/B5267/ihmUcFA==
    -----END RSA PRIVATE KEY-----