apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}-config
data:
  ignite-config.xml: |-
{{ .Files.Get "ignite-config.xml" | indent 4}}
            <property name="discoverySpi">
                <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                        <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                            <constructor-arg>
                                <bean class="org.apache.ignite.kubernetes.configuration.KubernetesConnectionConfiguration">
                                    <property name="namespace" value="{{ .Release.Namespace }}" />
                                    <property name="serviceName" value="{{ include "ignite.fullname" . }}" />
                                </bean>
                            </constructor-arg>
                        </bean>
                    </property>
                </bean>
            </property>
        </bean>
    </beans>
  log4j2-config.xml: |-
{{ .Files.Get "log4j2-config.xml" | indent 4}}