resource_group_name = "test-rg"
location            = "East US"
nsg_name            = "test-nsg"
vnet_name           = "test-vnet"
vnet_cidr           = "10.0.0.0/16"
aks_subnet_name     = "subnet-aks"
aks_subnet_cidr     = "10.0.0.0/20"
gw_subnet_name      = "GatewaySubnet"
gw_subnet_cidr      = "10.0.16.0/27"
public_ip_name      = "test-public-ip"
vnet_gw_name        = "test-vnet-gw"
vnet_gw_type        = "Vpn"
vnet_gw_vpn_type    = "RouteBased"
vnet_gw_sku         = "VpnGw2AZ"
vnet_gw_generation  = "Generation2"
vpn_cidr            = "100.0.0.0/24"
vpn_root_cert       = "MIICvjCCAaYCCQCzfR7KXSD7kDANBgkqhkiG9w0BAQsFADAhMR8wHQYDVQQDDBbD osKAwp1NeUF6dXJlVlBOw6LCgMKdMB4XDTIyMTEwMzIwNTMxM1oXDTMyMTAzMTIw NTMxM1owITEfMB0GA1UEAwwWw6LCgMKdTXlBenVyZVZQTsOiwoDCnTCCASIwDQYJ KoZIhvcNAQEBBQADggEPADCCAQoCggEBALCbuD3Dbf2Vg1Bm+ERutGAGfLV6c4Pl WlrNVgudp57TaTXfpFqo8l5D7gq3hlOyd3DuXbHcogbdIAYnngm9l9+er7Ejyh/3 9CkEjZ7OevIGI2pJkazKX8qS+SbiS+Fpqvy4sfdVDI/2Tv+LJ/lmCWwM4ZGov+Ek G12VMHwdRMQ+nyd8sXgt3hbEUqVISYN+qmSkq0U0Yj5Yf1HCIF0YZlYYEnN4z/Vi +SL6O3/8WGqQu2SotyiGpF5rqz80iTpg0D+tGVpySgKGPWuEXkJKyYEbUkMCT4aH I3OTNyliEKlkx91Hkv5Uc4MF3e+gMCZGrnTLKpb5j8xqAylM+RS+v+sCAwEAATAN BgkqhkiG9w0BAQsFAAOCAQEAKXhxw6PlmWesVlxJB+CEozyc2nBj0fEBoPPTEgBY Q7+VCztCRb6uLaVbMK6P19Ay+QnbUWDzyhU2mQveH2i/G4b1vTT5nExpOGF35uEG dtwQSM1rZje9av/qPhgxMhjxfRsI1nComJWnLpyuSMuUqj0aykJZf7nHnvI1qI30 VP6qWyd7OkbeHH9NlHukLiqW/h50fvmJPWAczm+7FWhjYDrsl2f8QQfC1E8U6K84 AKAiQTN6961Z8koKTF4y2Wgcl6DOqhI2KAUlcB/BQfqlL5Qj8vAgvxmplMY8w/V5 Uxk18JeGyaQKwrSh6ABGfeRQiWU3ZAWKhnKPGhveJhknUA=="