frontend:
  deployment:
    name: frontend-deployment
    app: frontend
    replicas: 1
    image: myacr/demo
    tag: frontend
    containerPort: 8080

  service:
    name: frontend-service
    port: 80
    type: LoadBalancer