apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "geo-server.fullname" . }}
spec:
  capacity:
    storage: {{.Values.volume.storage}}
  accessModes:
    - {{.Values.volume.accessModes}}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/{{ include "geo-server.fullname" . }}-data