apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "geo-server.fullname" . }}
spec:
  accessModes:
    - {{.Values.volume.accessModes}}
  resources:
    requests:
      storage: {{.Values.volume.storage}}
  volumeName: {{ include "geo-server.fullname" . }}