apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
type: Opaque
data:
  password: Y2hhbmdlbWU=
  elastic-username: ZWxhc3RpYw==
  kibana-username: a2liYW5hX3N5c3RlbQ==
  logstash-username: bG9nc3Rhc2hfc3lzdGVt