apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.express.service.name }}
spec:
  selector:
    app: {{ .Values.express.deployment.app }}
  type: {{ .Values.express.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.express.service.port }}
      targetPort: {{ .Values.express.deployment.containerPort }}