apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: {{ .Values.secret.type }}
data:
  mongo-root-username: {{ .Values.secret.username }}
  mongo-root-password: {{ .Values.secret.password }}