apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        - name: {{.Values.deployment.logenv}}
          value: {{.Values.deployment.logpath}}
        - name: {{.Values.deployment.configEnv}}
          value: {{.Values.deployment.configPath}}
        volumeMounts:
        - name: {{.Values.deployment.mountName}}
          mountPath: {{.Values.deployment.mountPath}}
        - name: {{.Values.deployment.configMount}}
          mountPath: {{.Values.deployment.configPath}}
      volumes:
        - name: {{.Values.deployment.configMount}}
          configMap:
            name: {{.Values.deployment.configName}}
            items:
              - key: {{.Values.deployment.configKey}}
                path: {{.Values.deployment.configKey}}
        - name: {{.Values.deployment.mountName}}
          persistentVolumeClaim:
            claimName: {{.Values.pvc.name}}