apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.deployment.app }}
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        env:
        - name: RABBITMQ_LOGS
          value: "/mnt/blob"
        volumeMounts:
        - name: mypv221
          mountPath: "/mnt/blob"
      volumes:
        - name: mypv221
          persistentVolumeClaim:
            claimName: pvc-blob-fuse