apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: {{ .Values.secret.type }}
data:
  azurestorageaccountname: {{ .Values.secret.azurestorageaccountname }}
  azurestorageaccountkey: {{ .Values.secret.azurestorageaccountkey }}