apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  labels:
    app: {{ .Values.frontend.deployment.app }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.deployment.app }}
        image: "{{ .Values.frontend.deployment.image }}:{{ .Values.frontend.deployment.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.deployment.containerPort }}       
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
spec:
  selector:
    app: {{ .Values.frontend.deployment.app }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.deployment.containerPort }}