apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  labels:
    app: {{ .Values.frontend.deployment.app }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.deployment.app }}
        image: "{{ .Values.frontend.deployment.image }}:{{ .Values.frontend.deployment.tag }}"
        imagePullPolicy: {{ .Values.frontend.deployment.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.deployment.containerPort }}
        env:
        - name: {{ .Values.env.JDBC_CONNECTION.name }}
          value: {{ .Values.env.JDBC_CONNECTION.value }}
        - name: {{ .Values.env.READ_UNCOMMITTED_JDBC_CONNECTION.name }}
          value: {{ .Values.env.READ_UNCOMMITTED_JDBC_CONNECTION.value }}
        - name: {{ .Values.env.REPORTING_JDBC_CONNECTION.name }}
          value: {{ .Values.env.REPORTING_JDBC_CONNECTION.value }}
      #   volumeMounts:
      #   - name: {{ .Values.mount.name }}
      #     mountPath: {{ .Values.mount.path }}
      # volumes:
      #   - name: {{ .Values.mount.name }}
      #     persistentVolumeClaim:
      #       claimName: {{ .Values.pvc.name }}