apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
  labels:
    app: {{ .Values.frontend.deployment.app }}
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.deployment.app }}
    spec:
      containers:
      - name: {{ .Values.frontend.deployment.app }}
        image: "{{ .Values.frontend.deployment.image }}:{{ .Values.frontend.deployment.tag }}"
        ports:
        - containerPort: {{ .Values.frontend.deployment.containerPort }}