apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.tlsSecret.name }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ .Values.frontend.service.name }}
          servicePort: {{ .Values.frontend.service.port }}