apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elastic.service.name }}-data
spec:
  selector:
    app: {{ .Values.elastic.deployment.app }}-master
  type: ClusterIP
  ports:
    - name: internal
      protocol: TCP
      port: {{ .Values.elastic.deployment.containerPortDB }}
      targetPort: {{ .Values.elastic.deployment.containerPortDB }}
    - name: transport
      protocol: TCP
      port: {{ .Values.elastic.deployment.containerPortTrans }}
      targetPort: {{ .Values.elastic.deployment.containerPortTrans }}