apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: filestream
      id: my-filestream-id
      paths:
        - /mnt/blob/rabbit.log
        - /var/log/messages
        - /var/log/*.log

    output.logstash:
      hosts: ['logstash-service']