apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    # filebeat.inputs:
    # - type: filestream
    #   enable: true
    #   id: my-filestream-id
    #   paths:
    #     - /mnt/blob/rabbit.log

  filebeat.autodiscover:
    providers:
      - type: kubernetes
        hints.enabled: true
        hints.default_config:
          type: container
          paths:
            - /var/log/containers/*.log

    output.logstash:
      hosts: ['logstash-service']