apiVersion: apps/v1
kind: DeamonSet
metadata:
  name: {{ .Values.filebeat.deployment.name }}
  labels:
    app: {{ .Values.filebeat.deployment.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.filebeat.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.filebeat.deployment.app }}
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/fileset.stdout: log
        co.elastic.logs/pipeline: custom-pipeline
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: {{ .Values.filebeat.deployment.app }}
        image: "{{ .Values.filebeat.deployment.image }}:{{ .Values.filebeat.deployment.tag }}"
        imagePullPolicy: {{ .Values.filebeat.deployment.pullPolicy }}
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: rabbit
          mountPath: /mnt/blob
      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      - name: rabbit
        persistentVolumeClaim:
            claimName: rabbit-pvc