apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: filestream
      enable: true
      id: my-filestream-id
      paths:
        - /mnt/blob/rabbit.log

    output.logstash:
      hosts: ['logstash-service']