apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.service.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
spec:
  selector:
    app: {{ .Values.kibana.deployment.app }}
  type: {{ .Values.kibana.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.deployment.containerPort }}