apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
    logstash.conf: |
        input {
        beats {
            port => 5044
        }
        }
        filter {
        if [fields][log-source] == "logfile" {
            grok {
                match => { "message" => "%{TIMESTAMP_ISO8601:time}:%{WORD:service} %{LOGLEVEL:loglevel} %{DATA:thread_name} \[%{DATA:src_file}:%{NUMBER:line}\] - %{GREEDYDATA:msg}" }
            }
            mutate {
                add_field => { "tmp_path" => "%{[log][file][path]}" }
            }
            mutate {
                split => ["tmp_path", "#"]
                add_field => { "kubernetes.node.name" => "%{tmp_path[2]}" }
                add_field => { "kubernetes.namespace" => "%{tmp_path[3]}" }
                add_field => { "tmp_podname" => "%{tmp_path[4]}" }
            }
            mutate {
                split => ["tmp_podname", "."]
                add_field => { "kubernetes.pod.name" => "%{tmp_podname[0]}" }
            }
            mutate {
                remove_field => [ "tmp_path", "tmp_podname" ]
            }
        }
        }
        output {
        elasticsearch {
            hosts => ["elastic-search-service:80"]
        }
        }
    logstash.yml: |
        # http.host: "0.0.0.0"
        path.config: /usr/share/logstash/pipeline
        xpack.monitoring.enabled: true
        xpack.monitoring.elasticsearch.ssl.verification_mode: none