apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}
spec:
  accessModes:
    - {{.Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{.Values.pvc.storage}}
  volumeName: {{.Values.volume.name}}
  storageClassName: azurefile-csi