apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.volume.name}}
spec:
  capacity:
    storage: {{.Values.volume.storage}}
  accessModes:
    - {{.Values.volume.accessModes}}
  persistentVolumeReclaimPolicy: {{.Values.volume.reclaimPolicy}}
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Values.volume.handle }}
    volumeAttributes:
      resourceGroup: aks-rg
      shareName: {{ .Values.volume.sharename }}
    nodeStageSecretRef:
      name: {{ .Values.secret.name }}
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl