apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.volume.name}}
spec:
  capacity:
    storage: {{.Values.volume.storage}}
  accessModes:
    - {{.Values.volume.accessModes}}
  persistentVolumeReclaimPolicy: {{.Values.volume.reclaimPolicy}}
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: {{.Values.volume.handle}}
    volumeAttributes:
      fsType: ext4
      cachingMode: None