controller:
  image:
    repository: k8s.gcr.io/ingress-nginx/controller
    pullPolicy: IfNotPresent
    tag: "v0.44.0"

admission:
  create:
    image:
      repository: docker.io/jettech/kube-webhook-certgen
      pullPolicy: IfNotPresent
      tag: "v1.5.1"
  patch:
    image:
      repository: docker.io/jettech/kube-webhook-certgen
      pullPolicy: IfNotPresent
      tag: "v1.5.1"

ingress:
  class: nginx

serviceAccount:
  create: true

service:
  type: LoadBalancer
  annotations: {
    service.beta.kubernetes.io/azure-load-balancer-internal: "true",
    service.beta.kubernetes.io/azure-pls-create: "true",
    azure-load-balancer-health-probe-request-path: "/healthz"
  }