controller:
  image:
    repository: k8s.gcr.io/ingress-nginx/controller
    pullPolicy: IfNotPresent
    tag: "v0.44.0@sha256:3dd0fac48073beaca2d67a78c746c7593f9c575168a17139a9955a82c63c4b9a"

admission:
  create:
    image:
      repository: docker.io/jettech/kube-webhook-certgen
      pullPolicy: IfNotPresent
      tag: "v1.5.1"
  patch:
    image:
      repository: docker.io/jettech/kube-webhook-certgen
      pullPolicy: IfNotPresent
      tag: "v1.5.1"

ingress:
  class: nginx

serviceAccount:
  create: true

service:
  type: LoadBalancer
  annotations: {
    service.beta.kubernetes.io/azure-load-balancer-internal: "true",
    service.beta.kubernetes.io/azure-pls-create: "true",
    azure-load-balancer-health-probe-request-path: "/healthz"
  }