controller:
  image:
    repository: nginx/nginx-ingress
    pullPolicy: IfNotPresent
    tag: "latest"

admission:
  create:
    image:
      repository: rpkatz/kube-webhook-certgen
      pullPolicy: IfNotPresent
      tag: "v1.5.2"
  patch:
    image:
      repository: rpkatz/kube-webhook-certgen
      pullPolicy: IfNotPresent
      tag: "v1.5.2"

ingress:
  class: nginx

serviceAccount:
  create: true

service:
  type: LoadBalancer
  annotations: {
    service.beta.kubernetes.io/azure-load-balancer-internal: "true",
    service.beta.kubernetes.io/azure-pls-create: "true",
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
  }