apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: myblob22_testcont1
    volumeAttributes:
      resourceGroup: MC_aks-rg_aks-poc_eastus
      storageAccount: myblob22
      containerName: testcont1
      protocol: nfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blob-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob-nfs
  storageClassName: azureblob-nfs-premium
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-blob
spec:
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-blob
      volumeMounts:
        - name: mount-nfs
          mountPath: "/mnt/blob/nfs"
  volumes:
    - name: mount-nfs
      persistentVolumeClaim:
        claimName: pvc-blob-nfs