elastic:
  deployment:
    name: elastic-search
    app: elastic-search
    replicas: 3
    image: elasticsearch
    tag: 8.5.3
    containerPortDB: 9200
    containerPortDBName: db
    containerPortTrans: 9300
    containerPortTransName: trans
    pullPolicy: Always

  service:
    name: elastic-search-service
    port: 80
    type: LoadBalancer

logstash:
  deployment:
    name: logstash-deployment
    app: logstash
    replicas: 1
    image: logstash
    tag: 8.5.3
    containerPort: 5044
    pullPolicy: Always

  service:
    name: logstash-service
    port: 5044

filebeat:
  deployment:
    name: filebeat-deployment
    app: filebeat
    image: elastic/filebeat
    tag: 8.5.3
    pullPolicy: Always

kibana:
  deployment:
    name: kibana-deployment
    app: kibana
    replicas: 1
    image: kibana
    tag: 8.5.3
    containerPort: 5601
    pullPolicy: Always

  service:
    name: kibana-service
    port: 80
    type: LoadBalancer

fleet:
  deployment:
    name: fleetdeployment
    app: elasticagent
    replicas: 1
    image: docker.elastic.co/beats/elastic-agent
    tag: 8.5.3
    containerPort: 8220
    pullPolicy: Always

  service:
    name: fleetservice
    port: 443
    type: LoadBalancer
  
ingress:
  name: elk-ingress
  class: nginx
  path: /
  pathType: Prefix

secret:
  name: storage-secret
  type: Opaque
  azurestorageaccountname: myblob221
  azurestorageaccountkey: "G/a0XHwQ2uU59PqWVmWLIJfjZnhnJDYDBR7p0tFxpCI9PyGBrgSJQ33MGalVHvamSKJO7IN5U1uL+AStKt2drQ=="

volume:
  name: ec-pv
  storage: 10Gi
  accessModes: ReadWriteOnce
  reclaimPolicy: Retain
  handle: "/subscriptions/863fda5d-6174-4448-8f7b-f8b0f9008431/resourcegroups/MC_aks-rg_aks-poc-1_eastus/providers/Microsoft.Compute/disks/mydisk221"
  containerName: eccontainer

pvc:
  name: ec-pvc
  accessModes: ReadWriteOnce
  storage: 10Gi