elastic:
  deployment:
    name: elastic-search-deployment
    app: elastic-search
    replicas: 1
    image: elasticsearch
    tag: 8.5.3
    containerPortDB: 9200
    containerPortDBName: db
    containerPortTrans: 9300
    containerPortTransName: trans
    pullPolicy: Always

  service:
    name: elastic-search-service
    port: 80
    type: LoadBalancer

logstash:
  deployment:
    name: logstash-deployment
    app: logstash
    replicas: 1
    image: logstash
    tag: 8.5.3
    containerPort: 5044
    pullPolicy: Always

  service:
    name: logstash-service
    port: 5044

filebeat:
  deployment:
    name: filebeat-deployment
    app: filebeat
    image: elastic/filebeat
    tag: 8.5.3
    pullPolicy: Always

kibana:
  deployment:
    name: kibana-deployment
    app: kibana
    replicas: 1
    image: kibana
    tag: 8.5.3
    containerPort: 5601
    pullPolicy: Always

  service:
    name: kibana-service
    port: 80
    type: LoadBalancer
  
ingress:
  name: elk-ingress
  class: nginx
  path: /
  pathType: Prefix

secret:
  name: storage-secret
  type: Opaque
  azurestorageaccountname: myblob221
  azurestorageaccountkey: "G/a0XHwQ2uU59PqWVmWLIJfjZnhnJDYDBR7p0tFxpCI9PyGBrgSJQ33MGalVHvamSKJO7IN5U1uL+AStKt2drQ=="

volume:
  name: ec-pv
  storage: 10Gi
  accessModes: ReadWriteMany
  reclaimPolicy: Retain
  handle: ecpv221
  containerName: eccontainer

pvc:
  name: ec-pvc
  accessModes: ReadWriteMany
  storage: 10Gi