deployment:
  name: rabbitmq-deployment
  app: rabbitmq
  replicas: 1
  image: myacr221.azurecr.io/rabbitmq
  tag: v1.0
  containerPort: 15672
  pullPolicy: Always
  logenv: RABBITMQ_LOGS
  logpath: "/mnt/blob/rabbit.log"
  userenv: RABBITMQ_DEFAULT_USER
  passenv: RABBITMQ_DEFAULT_PASS
  mountName: logpv
  mountPath: "/mnt/blob"
  configEnv: RABBITMQ_CONFIG_FILES
  configName: rabbitmq-config
  configMount: config-volume
  configKey: rabbitmq.conf
  configPath: "/etc/rabbitmq/conf.d"
  pluginMount: plugin-volume
  pluginKey: enabled_plugins
  pluginPath: "/etc/rabbitmq"


service:
  name: rabbitmq-service
  port: 80
  type: LoadBalancer

secret:
  name: storage-secret
  type: Opaque
  azurestorageaccountname: myblob221
  azurestorageaccountkey: "ezfxxW0gsext9cK7uOVkH2N07xAru7wzfnAT6q+6P26G9Ld65f+wyHu5HUs527PmLvQLBStIl1gf+AStLPWOuQ=="

volume:
  name: rabbit-pv
  storage: 10Gi
  accessModes: ReadWriteMany
  reclaimPolicy: Retain
  handle: rabbitpv221
  containerName: mycontainer

pvc:
  name: rabbit-pvc
  accessModes: ReadWriteMany
  storage: 10Gi