deployment:
  name: rabbitmq-deployment
  app: rabbitmq
  replicas: 1
  image: myacr221.azurecr.io/rabbitmq
  tag: v1.0
  containerPort: 15672
  pullPolicy: Always
  logenv: RABBITMQ_LOGS
  logpath: "/mnt/blob/rabbit.log"
  userenv: RABBITMQ_DEFAULT_USER
  passenv: RABBITMQ_DEFAULT_PASS
  mountName: logpv
  mountPath: "/mnt/blob"

service:
  name: rabbitmq-service
  port: 80
  type: LoadBalancer

secret:
  name: storage-secret
  type: Opaque
  azurestorageaccountname: myblob221
  azurestorageaccountkey: "ezfxxW0gsext9cK7uOVkH2N07xAru7wzfnAT6q+6P26G9Ld65f+wyHu5HUs527PmLvQLBStIl1gf+AStLPWOuQ=="

crsecret:
  name: cred-secret
  type: Opaque
  username: dXNlcg==
  password: cGFzc3dvcmQ=

volume:
  name: rabbit-pv
  storage: 10Gi
  accessModes: ReadWriteMany
  reclaimPolicy: Retain
  handle: rabbitpv221
  containerName: mycontainer

pvc:
  name: rabbit-pvc
  accessModes: ReadWriteMany
  storage: 10Gi
