---
- hosts: master
  become: yes
  tasks:
    - name: install nfs-utils
      yum: name=nfs-utils state=latest

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/test
        state: directory
        owner: root
        group: root
        mode: '0644'

    - name: enable rpcbind nfslock nfs
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - rpcbind
        - nfslock
        - nfs

    - name: open ports
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - mountd
        - rpc-bind

    - name: relode firewalld
      command: firewall-cmd --reload

    - name: Copy exports file.
      template:
        src: ./exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644

    - name: NFS apply change configrue
      shell: systemctl reload nfs;exportfs -a