frontend:
  deployment:
    name: frontend-deployment
    app: frontend
    replicas: 1
    image: myacr221.azurecr.io/springboot
    tag: v1.0
    containerPort: 8080
    pullPolicy: Always

  service:
    name: frontend-service
    port: 80
    type: LoadBalancer

namespace:
  name: test
  lable: demo