deployment:
  name: ignite-deployment
  app: ignite
  replicas: 1
  image: myacr221.azurecr.io/ignite
  tag: v1.0
  containerPort: 8080
  pullPolicy: Always

service:
  name: ignite-service
  port: 80
  type: LoadBalancer