- hosts: all
  become: yes
  tasks:
    - name: install Docker
      yum:
        name: docker
        state: present
        update_cache: true

    - name: start Docker
      service:
        name: docker
        state: started

    - name: disable SELinux
      command: setenforce 0

    - name: disable SELinux on reboot
      selinux:
        state: disabled

    - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present

    - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present

    - name: add Kubernetes' YUM repository
      yum_repository:
        name: Kubernetes
        description: Kubernetes YUM repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        gpgcheck: yes

    - name: install kubelet
      yum:
        name: kubelet-1.23.4
        state: present
        update_cache: true

    - name: install kubeadm
      yum:
        name: kubeadm-1.23.4
        state: present

    - name: start kubelet
      service:
        name: kubelet
        enabled: yes
        state: started

    - name: start firewalld
      service:
        name: firewalld
        enabled: yes
        state: started
    
    - name: open ports
      firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        state: enabled
      with_items:
       - { port: "6443", proto: "tcp" }
       - { port: "2379-2380", proto: "tcp" }
       - { port: "10250-10252", proto: "tcp" }
       - { port: "10259", proto: "tcp" }
       - { port: "10257", proto: "tcp" }
       - { port: "6783", proto: "tcp" }
       - { port: "30000-32767", proto: "tcp" }
       - { port: "5473", proto: "tcp" }
       - { port: "6783-6784", proto: "udp" }
       - { port: "4789", proto: "udp" }
       - { port: "8285", proto: "udp" }
       - { port: "8472", proto: "udp" }

    - name: relode firewalld
      command: firewall-cmd --reload

- hosts: master
  become: yes
  tasks:
    - name: install kubectl
      yum:
        name: kubectl-1.23.4
        state: present
        allow_downgrade: yes